// <auto-generated />
namespace EShop.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relation_Brand_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relation_Brand_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240951442_Relation_Brand_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
